//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosedLoop) DeepCopyInto(out *ClosedLoop) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosedLoop.
func (in *ClosedLoop) DeepCopy() *ClosedLoop {
	if in == nil {
		return nil
	}
	out := new(ClosedLoop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClosedLoop) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosedLoopD) DeepCopyInto(out *ClosedLoopD) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosedLoopD.
func (in *ClosedLoopD) DeepCopy() *ClosedLoopD {
	if in == nil {
		return nil
	}
	out := new(ClosedLoopD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClosedLoopD) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosedLoopDList) DeepCopyInto(out *ClosedLoopDList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClosedLoopD, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosedLoopDList.
func (in *ClosedLoopDList) DeepCopy() *ClosedLoopDList {
	if in == nil {
		return nil
	}
	out := new(ClosedLoopDList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClosedLoopDList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosedLoopDSpec) DeepCopyInto(out *ClosedLoopDSpec) {
	*out = *in
	out.Monitoring = in.Monitoring
	in.Decision.DeepCopyInto(&out.Decision)
	in.Execution.DeepCopyInto(&out.Execution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosedLoopDSpec.
func (in *ClosedLoopDSpec) DeepCopy() *ClosedLoopDSpec {
	if in == nil {
		return nil
	}
	out := new(ClosedLoopDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosedLoopDStatus) DeepCopyInto(out *ClosedLoopDStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosedLoopDStatus.
func (in *ClosedLoopDStatus) DeepCopy() *ClosedLoopDStatus {
	if in == nil {
		return nil
	}
	out := new(ClosedLoopDStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosedLoopList) DeepCopyInto(out *ClosedLoopList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClosedLoop, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosedLoopList.
func (in *ClosedLoopList) DeepCopy() *ClosedLoopList {
	if in == nil {
		return nil
	}
	out := new(ClosedLoopList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClosedLoopList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosedLoopSpec) DeepCopyInto(out *ClosedLoopSpec) {
	*out = *in
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	in.Decision.DeepCopyInto(&out.Decision)
	in.Execution.DeepCopyInto(&out.Execution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosedLoopSpec.
func (in *ClosedLoopSpec) DeepCopy() *ClosedLoopSpec {
	if in == nil {
		return nil
	}
	out := new(ClosedLoopSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClosedLoopStatus) DeepCopyInto(out *ClosedLoopStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClosedLoopStatus.
func (in *ClosedLoopStatus) DeepCopy() *ClosedLoopStatus {
	if in == nil {
		return nil
	}
	out := new(ClosedLoopStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Decision) DeepCopyInto(out *Decision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Decision.
func (in *Decision) DeepCopy() *Decision {
	if in == nil {
		return nil
	}
	out := new(Decision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Decision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionD) DeepCopyInto(out *DecisionD) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionD.
func (in *DecisionD) DeepCopy() *DecisionD {
	if in == nil {
		return nil
	}
	out := new(DecisionD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DecisionD) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionDKind) DeepCopyInto(out *DecisionDKind) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionDKind.
func (in *DecisionDKind) DeepCopy() *DecisionDKind {
	if in == nil {
		return nil
	}
	out := new(DecisionDKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionDList) DeepCopyInto(out *DecisionDList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DecisionD, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionDList.
func (in *DecisionDList) DeepCopy() *DecisionDList {
	if in == nil {
		return nil
	}
	out := new(DecisionDList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DecisionDList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionDObject) DeepCopyInto(out *DecisionDObject) {
	*out = *in
	out.DecisionKind = in.DecisionKind
	in.DecisionPolicies.DeepCopyInto(&out.DecisionPolicies)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionDObject.
func (in *DecisionDObject) DeepCopy() *DecisionDObject {
	if in == nil {
		return nil
	}
	out := new(DecisionDObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionDPolicies) DeepCopyInto(out *DecisionDPolicies) {
	*out = *in
	in.PrioritySpec.DeepCopyInto(&out.PrioritySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionDPolicies.
func (in *DecisionDPolicies) DeepCopy() *DecisionDPolicies {
	if in == nil {
		return nil
	}
	out := new(DecisionDPolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionDSpec) DeepCopyInto(out *DecisionDSpec) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionDSpec.
func (in *DecisionDSpec) DeepCopy() *DecisionDSpec {
	if in == nil {
		return nil
	}
	out := new(DecisionDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionDStatus) DeepCopyInto(out *DecisionDStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionDStatus.
func (in *DecisionDStatus) DeepCopy() *DecisionDStatus {
	if in == nil {
		return nil
	}
	out := new(DecisionDStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionKind) DeepCopyInto(out *DecisionKind) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionKind.
func (in *DecisionKind) DeepCopy() *DecisionKind {
	if in == nil {
		return nil
	}
	out := new(DecisionKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionList) DeepCopyInto(out *DecisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Decision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionList.
func (in *DecisionList) DeepCopy() *DecisionList {
	if in == nil {
		return nil
	}
	out := new(DecisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DecisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionObject) DeepCopyInto(out *DecisionObject) {
	*out = *in
	out.DecisionKind = in.DecisionKind
	in.DecisionPolicies.DeepCopyInto(&out.DecisionPolicies)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionObject.
func (in *DecisionObject) DeepCopy() *DecisionObject {
	if in == nil {
		return nil
	}
	out := new(DecisionObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionPolicies) DeepCopyInto(out *DecisionPolicies) {
	*out = *in
	in.PrioritySpec.DeepCopyInto(&out.PrioritySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionPolicies.
func (in *DecisionPolicies) DeepCopy() *DecisionPolicies {
	if in == nil {
		return nil
	}
	out := new(DecisionPolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionSpec) DeepCopyInto(out *DecisionSpec) {
	*out = *in
	in.DecisionPolicies.DeepCopyInto(&out.DecisionPolicies)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionSpec.
func (in *DecisionSpec) DeepCopy() *DecisionSpec {
	if in == nil {
		return nil
	}
	out := new(DecisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionStatus) DeepCopyInto(out *DecisionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionStatus.
func (in *DecisionStatus) DeepCopy() *DecisionStatus {
	if in == nil {
		return nil
	}
	out := new(DecisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Execution) DeepCopyInto(out *Execution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Execution.
func (in *Execution) DeepCopy() *Execution {
	if in == nil {
		return nil
	}
	out := new(Execution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Execution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionD) DeepCopyInto(out *ExecutionD) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionD.
func (in *ExecutionD) DeepCopy() *ExecutionD {
	if in == nil {
		return nil
	}
	out := new(ExecutionD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExecutionD) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionDList) DeepCopyInto(out *ExecutionDList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExecutionD, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionDList.
func (in *ExecutionDList) DeepCopy() *ExecutionDList {
	if in == nil {
		return nil
	}
	out := new(ExecutionDList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExecutionDList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionDSpec) DeepCopyInto(out *ExecutionDSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionDSpec.
func (in *ExecutionDSpec) DeepCopy() *ExecutionDSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionDStatus) DeepCopyInto(out *ExecutionDStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionDStatus.
func (in *ExecutionDStatus) DeepCopy() *ExecutionDStatus {
	if in == nil {
		return nil
	}
	out := new(ExecutionDStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionList) DeepCopyInto(out *ExecutionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Execution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionList.
func (in *ExecutionList) DeepCopy() *ExecutionList {
	if in == nil {
		return nil
	}
	out := new(ExecutionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExecutionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionSpec) DeepCopyInto(out *ExecutionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionSpec.
func (in *ExecutionSpec) DeepCopy() *ExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionStatus) DeepCopyInto(out *ExecutionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionStatus.
func (in *ExecutionStatus) DeepCopy() *ExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(ExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoring) DeepCopyInto(out *Monitoring) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoring.
func (in *Monitoring) DeepCopy() *Monitoring {
	if in == nil {
		return nil
	}
	out := new(Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Monitoring) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringD) DeepCopyInto(out *MonitoringD) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringD.
func (in *MonitoringD) DeepCopy() *MonitoringD {
	if in == nil {
		return nil
	}
	out := new(MonitoringD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringD) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDKind) DeepCopyInto(out *MonitoringDKind) {
	*out = *in
	out.Source = in.Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDKind.
func (in *MonitoringDKind) DeepCopy() *MonitoringDKind {
	if in == nil {
		return nil
	}
	out := new(MonitoringDKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDList) DeepCopyInto(out *MonitoringDList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MonitoringD, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDList.
func (in *MonitoringDList) DeepCopy() *MonitoringDList {
	if in == nil {
		return nil
	}
	out := new(MonitoringDList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringDList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDObject) DeepCopyInto(out *MonitoringDObject) {
	*out = *in
	out.MonitoringKind = in.MonitoringKind
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDObject.
func (in *MonitoringDObject) DeepCopy() *MonitoringDObject {
	if in == nil {
		return nil
	}
	out := new(MonitoringDObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDPolicies) DeepCopyInto(out *MonitoringDPolicies) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TresholdKind != nil {
		in, out := &in.TresholdKind, &out.TresholdKind
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TresholdValue != nil {
		in, out := &in.TresholdValue, &out.TresholdValue
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDPolicies.
func (in *MonitoringDPolicies) DeepCopy() *MonitoringDPolicies {
	if in == nil {
		return nil
	}
	out := new(MonitoringDPolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDSpec) DeepCopyInto(out *MonitoringDSpec) {
	*out = *in
	out.Source = in.Source
	in.MonitoringPolicies.DeepCopyInto(&out.MonitoringPolicies)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDSpec.
func (in *MonitoringDSpec) DeepCopy() *MonitoringDSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDStatus) DeepCopyInto(out *MonitoringDStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDStatus.
func (in *MonitoringDStatus) DeepCopy() *MonitoringDStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoringDStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDv2) DeepCopyInto(out *MonitoringDv2) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDv2.
func (in *MonitoringDv2) DeepCopy() *MonitoringDv2 {
	if in == nil {
		return nil
	}
	out := new(MonitoringDv2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringDv2) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDv2List) DeepCopyInto(out *MonitoringDv2List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MonitoringDv2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDv2List.
func (in *MonitoringDv2List) DeepCopy() *MonitoringDv2List {
	if in == nil {
		return nil
	}
	out := new(MonitoringDv2List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringDv2List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDv2Spec) DeepCopyInto(out *MonitoringDv2Spec) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDv2Spec.
func (in *MonitoringDv2Spec) DeepCopy() *MonitoringDv2Spec {
	if in == nil {
		return nil
	}
	out := new(MonitoringDv2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringDv2Status) DeepCopyInto(out *MonitoringDv2Status) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringDv2Status.
func (in *MonitoringDv2Status) DeepCopy() *MonitoringDv2Status {
	if in == nil {
		return nil
	}
	out := new(MonitoringDv2Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringKind) DeepCopyInto(out *MonitoringKind) {
	*out = *in
	out.Source = in.Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringKind.
func (in *MonitoringKind) DeepCopy() *MonitoringKind {
	if in == nil {
		return nil
	}
	out := new(MonitoringKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringList) DeepCopyInto(out *MonitoringList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Monitoring, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringList.
func (in *MonitoringList) DeepCopy() *MonitoringList {
	if in == nil {
		return nil
	}
	out := new(MonitoringList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringObject) DeepCopyInto(out *MonitoringObject) {
	*out = *in
	out.MonitoringKind = in.MonitoringKind
	in.MonitoringPolicies.DeepCopyInto(&out.MonitoringPolicies)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringObject.
func (in *MonitoringObject) DeepCopy() *MonitoringObject {
	if in == nil {
		return nil
	}
	out := new(MonitoringObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringPolicies) DeepCopyInto(out *MonitoringPolicies) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TresholdKind != nil {
		in, out := &in.TresholdKind, &out.TresholdKind
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TresholdValue != nil {
		in, out := &in.TresholdValue, &out.TresholdValue
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringPolicies.
func (in *MonitoringPolicies) DeepCopy() *MonitoringPolicies {
	if in == nil {
		return nil
	}
	out := new(MonitoringPolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
	out.Source = in.Source
	in.MonitoringPolicies.DeepCopyInto(&out.MonitoringPolicies)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringStatus) DeepCopyInto(out *MonitoringStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringStatus.
func (in *MonitoringStatus) DeepCopy() *MonitoringStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoringv2) DeepCopyInto(out *Monitoringv2) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoringv2.
func (in *Monitoringv2) DeepCopy() *Monitoringv2 {
	if in == nil {
		return nil
	}
	out := new(Monitoringv2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Monitoringv2) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoringv2List) DeepCopyInto(out *Monitoringv2List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Monitoringv2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoringv2List.
func (in *Monitoringv2List) DeepCopy() *Monitoringv2List {
	if in == nil {
		return nil
	}
	out := new(Monitoringv2List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Monitoringv2List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoringv2Spec) DeepCopyInto(out *Monitoringv2Spec) {
	*out = *in
	in.MonitoringPolicies.DeepCopyInto(&out.MonitoringPolicies)
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoringv2Spec.
func (in *Monitoringv2Spec) DeepCopy() *Monitoringv2Spec {
	if in == nil {
		return nil
	}
	out := new(Monitoringv2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoringv2Status) DeepCopyInto(out *Monitoringv2Status) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoringv2Status.
func (in *Monitoringv2Status) DeepCopy() *Monitoringv2Status {
	if in == nil {
		return nil
	}
	out := new(Monitoringv2Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityDSpec) DeepCopyInto(out *PriorityDSpec) {
	*out = *in
	if in.PriorityRank != nil {
		in, out := &in.PriorityRank, &out.PriorityRank
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityDSpec.
func (in *PriorityDSpec) DeepCopy() *PriorityDSpec {
	if in == nil {
		return nil
	}
	out := new(PriorityDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrioritySpec) DeepCopyInto(out *PrioritySpec) {
	*out = *in
	if in.PriorityRank != nil {
		in, out := &in.PriorityRank, &out.PriorityRank
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrioritySpec.
func (in *PrioritySpec) DeepCopy() *PrioritySpec {
	if in == nil {
		return nil
	}
	out := new(PrioritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Source) DeepCopyInto(out *Source) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Source.
func (in *Source) DeepCopy() *Source {
	if in == nil {
		return nil
	}
	out := new(Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceD) DeepCopyInto(out *SourceD) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceD.
func (in *SourceD) DeepCopy() *SourceD {
	if in == nil {
		return nil
	}
	out := new(SourceD)
	in.DeepCopyInto(out)
	return out
}
